### ISSUE TITLE
CP4NA is broken, probably needs to update to latest level of operator

### ISSUE THREAD

**Issue by annumberhocker** [ibm-build-lab/terraform-ibm-cloud-pak#128]
Error when trying to create service account: 

error: error validating "STDIN": error validating data: ValidationError(ServiceAccount.metadata): unknown field "app" in io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta;

The invalid yaml is: 
```
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
  app: ibm-alm-prod
  name: alm-serviceaccount
  namespace: cp4na
imagePullSecrets:
- name: ibm-entitlement-key
```
